Repository adityyaa-10/monthly-wrap, pull requests merged in 2023-10, with the labels that each got.

#45 fix: minor bugs
  server/backend/settings.py
  server/requirements.txt
  server/users/migrations/0006_categories_projects.py
Labels: hacktoberfest, hacktoberfest-accepted

#46 Improved the UI of full blog page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FullBlogPage.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#48 fixed adding tech related categories
  frontend/src/components/BlogCreate.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#49 Updated README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
